create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name text not null default '',
  last_name text not null default '',
  email text not null default '',
  phone text not null default '',
  organization text not null default '',
  position text not null default '',
  city text not null default '',
  specialty text not null default ''
);

alter table public.registrations
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists first_name text not null default '',
  add column if not exists last_name text not null default '',
  add column if not exists email text not null default '',
  add column if not exists phone text not null default '',
  add column if not exists organization text not null default '',
  add column if not exists position text not null default '',
  add column if not exists city text not null default '',
  add column if not exists specialty text not null default '';

alter table public.registrations enable row level security;

drop policy if exists "Allow public registration inserts" on public.registrations;

create policy "Allow public registration inserts"
on public.registrations
for insert
to anon
with check (true);
